# Site settings
title: Sunwind Skies
header-img: img/home-bg.png
email: mavericktesini@gmail.com
copyright_name: Kiveo
description: > # this means to ignore newlines until "baseurl:"
  Adventure Together
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Kiveo
learn_profile: Kiveo
email_username: mavericktesini@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
